name: 'Update manifests'
description: 'Update micro service manifests'
inputs:
  name:
    description: 'Name of the micro service'
    required: true

  token:
    description: 'GitHub token'
    required: true

  target:
    description: 'Deployment target, [prod | dev]'
    required: true

  instances:
    description: 'Number of instances to run the micro service on'
    required: true

  version:
    description: 'Release version'
    required: true

  slack:
    description: 'Slack channel'
    required: true

  registry:
    description: 'Docker registry'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set PROD env
      shell: bash
      if: "${{ inputs.token }} == 'prod'"
      run: |
        echo "TOP_DOMAIN=app" >> $GITHUB_ENV
        echo "VERSION_TAG=${{ inputs.version }}" >> $GITHUB_ENV

    - name: Set DEV env
      shell: bash
      if: "${{ inputs.token }} != 'prod'"
      run: |
        echo "TOP_DOMAIN=app" >> $GITHUB_ENV
        echo "VERSION_TAG=${{ inputs.version }}-rc${{github.run_number}}" >> $GITHUB_ENV

    - name: Set env
      shell: bash
      run: |
        echo "TARGET_DEPLOY_DIR=./deployments/deployment/${{ inputs.target }}/${{ inputs.name }}" >> $GITHUB_ENV
        echo "TARGET_APP_DIR=./deployments/application/${{ inputs.target }}/${{ inputs.name }}" >> $GITHUB_ENV

    - name: Configure git
      shell: bash
      run: |
        git config --global user.email "devops@sysarb.se"
        git config --global user.name "Sysarb"

    - name: Checkout deployment
      uses: actions/checkout@v2
      with:
        repository: Sysarb/k8s-deployments
        token: ${{ inputs.token }}
        path: ./deployments

    - name: Update deployment manifests
      shell: bash
      run:  |
        mkdir -p ${{ env.TARGET_DEPLOY_DIR }}
        cp -a ./manifests/. ${{ env.TARGET_DEPLOY_DIR }}/
        test -e ${{ env.TARGET_DEPLOY_DIR }}/deploy.yaml && sed -i "s|${{ inputs.registry }}/${{ inputs.name }}:latest|${{ inputs.registry }}/${{ inputs.name }}:${{ env.VERSION_TAG }}|g" ${{ env.TARGET_DEPLOY_DIR }}/deploy.yaml
        test -e ${{ env.TARGET_DEPLOY_DIR }}/deploy.yaml && sed -i "s|\[INSTANCES\]|${{ inputs.instances }}|g" ${{ env.TARGET_DEPLOY_DIR }}/deploy.yaml
        test -e ${{ env.TARGET_DEPLOY_DIR }}/deploy.yaml && sed -i "s|\[VERSION\]|${{ env.VERSION_TAG }}|g" ${{ env.TARGET_DEPLOY_DIR }}/deploy.yaml
        test -e ${{ env.TARGET_DEPLOY_DIR }}/ingress.yaml && sed -i "s|\[TOP_DOMAIN\]|${{ env.TOP_DOMAIN }}|g" ${{ env.TARGET_DEPLOY_DIR }}/ingress.yaml

    - name: Update application manifest
      shell: bash
      run: |
        mkdir -p ${{ env.TARGET_APP_DIR }}
        cp -a ./deployments/templates/application.yaml ${{ env.TARGET_APP_DIR }}/
        test -e ${{ env.TARGET_APP_DIR }}/application.yaml && sed -i "s|\[NAME\]|${{ inputs.name }}|g" ${{ env.TARGET_APP_DIR }}/application.yaml
        test -e ${{ env.TARGET_APP_DIR }}/application.yaml && sed -i "s|\[PATH\]|deployment/${{ inputs.target }}/${{ inputs.name }}/|g" ${{ env.TARGET_APP_DIR }}/application.yaml
        test -e ${{ env.TARGET_APP_DIR }}/application.yaml && sed -i "s|\[SLACK_CHANNEL\]|${{ inputs.slack }}|g" ${{ env.TARGET_APP_DIR }}/application.yaml

    - name: Push deployment
      shell: bash
      run: |
        cd ./deployments
        git add .
        git commit -am "Updated deployments for ${{ inputs.name }}"
        git push
